name: Check External Release and Publish

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  check-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Get latest release tag from external repo
        id: get-external-release
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/TriliumNext/Trilium/releases/latest | jq -r '.tag_name')
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Read stored version
        id: read-stored-version
        run: |
          if [ -f "version.txt" ]; then
            STORED_TAG=$(cat version.txt)
            echo "stored_tag=$STORED_TAG" >> $GITHUB_OUTPUT
          else
            echo "stored_tag=" >> $GITHUB_OUTPUT
          fi

      - name: Check if new release is available
        id: check-version
        run: |
          if [ "${{ steps.get-external-release.outputs.latest_tag }}" != "${{ steps.read-stored-version.outputs.stored_tag }}" ]; then
            echo "is_new=true" >> $GITHUB_OUTPUT
            echo "New release found: ${{ steps.get-external-release.outputs.latest_tag }}"
          else
            echo "is_new=false" >> $GITHUB_OUTPUT
            echo "No new release."
          fi

      - name: Download, Process and Repack
        if: steps.check-version.outputs.is_new == 'true'
        run: |
          wget -O external_latest.zip https://github.com/TriliumNext/Trilium/releases/download/${{ steps.get-external-release.outputs.latest_tag }}/TriliumNotes-Server-${{ steps.get-external-release.outputs.latest_tag }}-linux-arm64.tar.xz
          tar xvf TriliumNotes-Server-${{ steps.get-external-release.outputs.latest_tag }}-linux-arm64.tar.xz -d extracted_external/
          # 此处加入你的自定义替换和修改操作
          rm -rf extracted_external/node
          rm -rf extracted_external/node_modules/better-sqlite3
          
          mkdir -p extracted_external/node/
          cp -r nodejs-v22.19.0/bin/ extracted_external/node/
          cp -r nodejs-v22.19.0/node_modules/better-sqlite3 extracted_external/node_modules/
          cd extracted_external
          tar cJf ../TriliumNotes-Server-${{ steps.get-external-release.outputs.latest_tag }}-termux-arm64.tar.xz ./*
          cd ..

      - name: Publish to Current Repository Release
        if: steps.check-version.outputs.is_new == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get-external-release.outputs.latest_tag }}
          name: Automated Build for ${{ steps.get-external-release.outputs.latest_tag }}
          body: |
            This is an automated release based on upstream version ${{ steps.get-external-release.outputs.latest_tag }}.
            **Source:** https://github.com/TriliumNext/Trilium
          files: TriliumNotes-Server-${{ steps.get-external-release.outputs.latest_tag }}-termux-arm64.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update stored version
        if: steps.check-version.outputs.is_new == 'true'
        run: |
          echo "${{ steps.get-external-release.outputs.latest_tag }}" > version.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add version.txt
          git commit -m "ci: update tracked external release to ${{ steps.get-external-release.outputs.latest_tag }}"
          git push
